--Depuración de códigos postales
delete from  zip_code_range_for_city;

--DEPURACIÓN MUNICIPIO Y LOCALIDAD
DELETE FROM CITY
WHERE CODE='ZAPOTITLÁN DEL RÍO' 
  AND COUNTY=(SELECT OID FROM COUNTY WHERE CODE='ZAPOTITLÁN DEL RÍO'  
    AND STATE=(SELECT OID from STATE WHERE CODE='OAXACA'));
       
DELETE FROM COUNTY WHERE CODE='ZAPOTITLÁN DEL RÍO'  
AND STATE=(SELECT OID from STATE WHERE CODE='OAXACA');

--ACTUALIZACIÓN DE CÓDIGOS DE MUNICIPIOS
UPDATE COUNTY SET CODE='DOLORES HIDALGO CUNA DE LA INDEPENDENCIA NACIONAL',NAME='MPIO DOLORES HIDALGO CUNA DE LA INDEPENDENCIA NACIONAL' WHERE STATE=(SELECT OID from state WHERE CODE='GUANAJUATO') AND CODE='DOLORES HIDALGO';
UPDATE COUNTY SET CODE='SILAO DE LA VICTORIA',NAME='MPIO SILAO DE LA VICTORIA' WHERE STATE=(SELECT OID from state WHERE CODE='GUANAJUATO') AND CODE='SILAO';
UPDATE COUNTY SET CODE='SAN PEDRO TLAQUEPAQUE',NAME='MPIO SAN PEDRO TLAQUEPAQUE' WHERE STATE=(SELECT OID from state WHERE CODE='JALISCO') AND CODE='TLAQUEPAQUE';
UPDATE COUNTY SET CODE='ACAMBAY DE RUÍZ CASTAÑEDA',NAME='MPIO ACAMBAY DE RUÍZ CASTAÑEDA' WHERE STATE=(SELECT OID from state WHERE CODE='MÉXICO') AND CODE='ACAMBAY';
UPDATE COUNTY SET CODE='TEOLOYUCAN',NAME='MPIO TEOLOYUCAN' WHERE STATE=(SELECT OID from state WHERE CODE='MÉXICO') AND CODE='TEOLOYUCÁN';
UPDATE COUNTY SET CODE='TLALTIZAPÁN DE ZAPATA',NAME='MPIO TLALTIZAPÁN DE ZAPATA' WHERE STATE=(SELECT OID from state WHERE CODE='MORELOS') AND CODE='TLALTIZAPÁN';
UPDATE COUNTY SET CODE='ZACUALPAN DE AMILPAS',NAME='MPIO ZACUALPAN DE AMILPAS' WHERE STATE=(SELECT OID from state WHERE CODE='MORELOS') AND CODE='ZACUALPAN';
UPDATE COUNTY SET CODE='EL CARMEN',NAME='MPIO EL CARMEN' WHERE STATE=(SELECT OID from state WHERE CODE='NUEVO LEÓN') AND CODE='CARMEN';
UPDATE COUNTY SET CODE='DOCTOR ARROYO',NAME='MPIO DOCTOR ARROYO' WHERE STATE=(SELECT OID from state WHERE CODE='NUEVO LEÓN') AND CODE='DR. ARROYO';
UPDATE COUNTY SET CODE='DOCTOR COSS',NAME='MPIO DOCTOR COSS' WHERE STATE=(SELECT OID from state WHERE CODE='NUEVO LEÓN') AND CODE='DR. COSS';
UPDATE COUNTY SET CODE='DOCTOR GONZÁLEZ',NAME='MPIO DOCTOR GONZÁLEZ' WHERE STATE=(SELECT OID from state WHERE CODE='NUEVO LEÓN') AND CODE='DR. GONZÁLEZ';
UPDATE COUNTY SET CODE='GENERAL BRAVO',NAME='MPIO GENERAL BRAVO' WHERE STATE=(SELECT OID from state WHERE CODE='NUEVO LEÓN') AND CODE='GRAL. BRAVO';
UPDATE COUNTY SET CODE='GENERAL ESCOBEDO',NAME='MPIO GENERAL ESCOBEDO' WHERE STATE=(SELECT OID from state WHERE CODE='NUEVO LEÓN') AND CODE='GRAL. ESCOBEDO';
UPDATE COUNTY SET CODE='GENERAL TERÁN',NAME='MPIO GENERAL TERÁN' WHERE STATE=(SELECT OID from state WHERE CODE='NUEVO LEÓN') AND CODE='GRAL. TERÁN';
UPDATE COUNTY SET CODE='GENERAL TREVIÑO',NAME='MPIO GENERAL TREVIÑO' WHERE STATE=(SELECT OID from state WHERE CODE='NUEVO LEÓN') AND CODE='GRAL. TREVIÑO';
UPDATE COUNTY SET CODE='GENERAL ZARAGOZA',NAME='MPIO GENERAL ZARAGOZA' WHERE STATE=(SELECT OID from state WHERE CODE='NUEVO LEÓN') AND CODE='GRAL. ZARAGOZA';
UPDATE COUNTY SET CODE='GENERAL ZUAZUA',NAME='MPIO GENERAL ZUAZUA' WHERE STATE=(SELECT OID from state WHERE CODE='NUEVO LEÓN') AND CODE='GRAL. ZUAZUA';
UPDATE COUNTY SET CODE='HEROICA CIUDAD DE JUCHITÁN DE ZARAGOZA',NAME='MPIO HEROICA CIUDAD DE JUCHITÁN DE ZARAGOZA' WHERE STATE=(SELECT OID from state WHERE CODE='OAXACA') AND CODE='JUCHITÁN DE ZARAGOZA';
UPDATE COUNTY SET CODE='SAN JUAN DEL ESTADO',NAME='MPIO SAN JUAN DEL ESTADO' WHERE STATE=(SELECT OID from state WHERE CODE='OAXACA') AND CODE='SAN JUAN DEL EDO';
UPDATE COUNTY SET CODE='SAN PEDRO TOTOLÁPAM',NAME='MPIO SAN PEDRO TOTOLÁPAM' WHERE STATE=(SELECT OID from state WHERE CODE='OAXACA') AND CODE='SAN PEDRO TOTOLAPA';
UPDATE COUNTY SET CODE='ATLTZAYANCA',NAME='MPIO ATLTZAYANCA' WHERE STATE=(SELECT OID from state WHERE CODE='TLAXCALA') AND CODE='ALTZAYANCA';
UPDATE COUNTY SET CODE='SAN DAMIÁN TEXÓLOC',NAME='MPIO SAN DAMIÁN TEXÓLOC' WHERE STATE=(SELECT OID from state WHERE CODE='TLAXCALA') AND CODE='SAN DAMIÁN TEXOLOC';
UPDATE COUNTY SET CODE='YAUHQUEMEHCAN',NAME='MPIO YAUHQUEMEHCAN' WHERE STATE=(SELECT OID from state WHERE CODE='TLAXCALA') AND CODE='YAUHQUEMECAN';
UPDATE COUNTY SET CODE='ZILTLALTÉPEC DE TRINIDAD SÁNCHEZ SANTOS',NAME='MPIO ZILTLALTÉPEC DE TRINIDAD SÁNCHEZ SANTOS' WHERE STATE=(SELECT OID from state WHERE CODE='TLAXCALA') AND CODE='ZITLALTEPEC DE TRINIDAD SÁNCHEZ SANTOS';
UPDATE COUNTY SET CODE='MEDELLÍN DE BRAVO',NAME='MPIO MEDELLÍN DE BRAVO' WHERE STATE=(SELECT OID from state WHERE CODE='VERACRUZ') AND CODE='MEDELLÍN';

COMMIT;